### ISSUE TITLE
Submit proposal to Nouns DAO

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#149]

**Comment by markoprljic** [comment]
Related https://publicnouns.wtf/ We're collaborating with them at Giveth.

**Comment by Zeptimus** [comment]
Can I get a contact from the Giveth crew, I'm trying to get on their discord server since yesterday but their bot is broken. For them I was thinking of swag shop since one of the types of proposals is  sending a Noun to outer space (what better than swag in the real world :D) https://docs.google.com/document/d/1mbg-TG_I5EExKMJIPzARUZ9aw3DLuKIq9syNiV7HeDE/edit# here is an initial draft but again would be better to get in their discord and talk to someone before posting a proposal in their forums IMO

PD: I tweeted them that their bot is not working but no luck there ^^'

**Comment by markoprljic** [comment]
You mean Nouns DAO, not Giveth?

**Comment by Zeptimus** [comment]
yeah 😅 i wanted to say if someone from giveth can link me to nouns dao contact

**Comment by ahmadabugosh** [comment]
@Zeptimus I just connected you with Jake at Giveth, he'd be a great person to talk to about existing conversations Giveth is having (with nouns dao or any other impact dao)

**Comment by Zeptimus** [comment]
Still have no access to discord, should I proceed and propose their forums?

**Comment by ahmadabugosh** [comment]
@Zeptimus Hey i think their Discord [maybe dead](https://twitter.com/pbrianandj/status/1587465449855295488), i would say try the forums

**Comment by Zeptimus** [comment]
got it! i had a initial draft ill tweak it and make a forum post.

**Comment by Zeptimus** [comment]
We need to hold a Nouns to propose the DAO which costs around 30-40eth we have been talking with Vlad who passed a proposal using the Gnar nouns but it seems we need to do something for gnar too and they already have a swag shop (ours is cooler). How should we proceed here?

**Comment by markoprljic** [comment]
So what I understood is we need 30-40 eth to submit a proposal? That seems out of question :D

**Comment by Zeptimus** [comment]
Yeah, unles there is a clear direction on how to aproach it its on the icebox for now

**Comment by markoprljic** [comment]
Ok.

**Comment by ahmadabugosh** [comment]
Yes, for sure let's ice it @Zeptimus (please move it on HS to "Closed Lost")

![giphy-ice](https://user-images.githubusercontent.com/4855928/204886779-426b56bd-1ece-4d39-9676-97b750ee8ec7.gif)


But I think we should explore some of the other forked smaller nouns projects (public nouns, lil nouns etc)

**Comment by Zeptimus** [comment]
failed
