### ISSUE TITLE
Project questionnaire or PRD to send to client

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#27]

**Comment by VMLVaske** [comment]
Created this draft: https://www.notion.so/giveth/Project-Questionnaire-PRD-6ec2b12396ac4d2187ce2848791e8dc6 

Proposal: If there is no more fields missing, I can make this into an airtable and we can link it directly on the General Magic Website for easy access + link it in our discord. 
If we automate this, we should either direct the incoming proposals into a specific discord channel or assign a person who is responsible to answer the potential client and start the process of onboarding a new process.

**Comment by markoprljic** [comment]
This is great! @VMLVaske I'm leaving some comments in the Notion. 
Please coordinate with @tomislavmamic and @Vyvy-vi on setup, automation and notifications.

**Comment by tomislavmamic** [comment]
I think that if we can use the template created by @VMLVaske in a way that a client can easily make a copy of it and start working on project details that can be reviewed and improved over time is the best way. Similarly to what I have done with ENS Shop documentation. It is all in Notion, share with them so they can add comment and content there too. We can then keep that document as a definition of the project.

I am not sure if we need to have this publicly available. If some prospective client wants to work with us, we can have them contact us, and then we create a copy of the doc and share it with them. This is not a lot of work because we don't have hundreds of clients. This also serves as a way for us to filter clients. After all we choose who we work for, we don't work for anyone who reaches out.

Having used this workflow that I mentioned with ENS, I can say it works well. There is no pressing issues that would require integrations with coda for now. 

There is the issue of using Zenhub/Github and Notion at the same time that @VMLVaske asked me about already. We should avoid doubling of data. Maybe the best approach would be to keep the Notion PRD at a higher level, only tracking epics and releases, while using Zenhub to track/manage individual issues/tasks and sprints. What do you think?

**Comment by tomislavmamic** [comment]
I've added 3 headings:
- Milestones
- Roadmap
- Payment schedule

**Comment by ahmadabugosh** [comment]
I created this Hubspot form, which I'm sending to clients for the time being: https://share-eu1.hsforms.com/1Uwmw0VEbQkCKA_lwwN9usQfkwqb
